apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: backend-external-secret
  namespace: production

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: backend-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: prod/three-tier/backend
